# -*- coding: utf-8 -*-
"""LP2023 - Avaliação 01 - Exercício 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4X-NiKhghB_MzMMB3tobAZGABI7Jiij

Curso de Tecnologia em Análise e Desenvolvimento de Sistemas da Faculdade de Tecnologia de São José do Rio Preto
# Avaliação de Linguagem de Programação
## Prof. Dr. Henrique Dezani

---
### SUBMISSÃO

Para submeter a sua solução, siga as etapas:
1. Faça o download do código python clicando em File -> Download -> Download.py
2. Acesse o _link_
3. Faça o login usando seu número de matrícula
4. Faça o _upload_ do Exercício (arquivo que fez o _download_ do Colab na etapa 2). 

Não se esqueça de escolher o exerício correto durante a submissão.

---
### ENUNCIADO DO EXERCÍCIO 2

Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.
Observando os termos no plural a colocação do "e", da vírgula entre outros.

Examplo

Dado o valor de entrada igual a `326`, a saída esperada é:

```
3 centenas, 2 dezenas e 6 unidades
```
Formato da entrada

A entrada consiste de um número inteiro positivo `numero` menor que 1000, informado pelo usuário.

Formato da saída

Descrição, por extenso, do número.

Entrada

```
12
```

Saída

```
1 dezena e duas unidades
```
"""

# Desenvolva seu programa aqui:
numero = int(input("digite um numero inteiro "))
count_dezena = 0
count_unidade = 0
count_centena = 0

while True:

  if numero >= 100:
    numero -= 100
    count_centena += 1
    # print(count_centena)
    # # print(numero)
  
    
  elif numero >= 10:
    numero -= 10
    count_dezena += 1
    # print(count_dezena)
    # # print(numero)
  

  elif numero > 0:
    numero -= 1
    count_unidade += 1
    # print(count_unidade)
    # # print(numero)
    break

if count_centena == 1:    
  print(f'{count_centena} centena')
else:
  print(f'{count_centena} centenas')

if count_dezena == 1:
  print(f'{count_dezena} dezena')
else:
  print(f'{count_dezena} dezenas')

  
if count_unidade == 1:
  print(f'{count_unidade} unidade')
else:
  print(f'{count_unidade} unidades')

print(count_centena + count_dezena + count_unidade)