# -*- coding: utf-8 -*-
"""LP - Avaliação 01 - Exercício 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10EX1f6yVRVhuHF4pJriImwTmGsrpdPki

Curso de Tecnologia em Análise e Desenvolvimento de Sistemas da Faculdade de Tecnologia de São José do Rio Preto
# Avaliação de Linguagem de Programação
## Prof. Dr. Henrique Dezani

---
### SUBMISSÃO

Para submeter a sua solução, siga as etapas:
1. Faça o download do código python clicando em File -> Download -> Download.py
2. Acesse o _link_
3. Faça o login usando seu número de matrícula
4. Faça o _upload_ do Exercício (arquivo que fez o _download_ do Colab na etapa 2). 

Não se esqueça de escolher o exerício correto durante a submissão.

---
### ENUNCIADO DO EXERCÍCIO 2

Leia um número inteiro `n` e imprima o quadrado do número `i`, sendo `i` todos os números positivos menores que `n`.

Examplo

A lista de inteiros não negativos menores do que `n = 3` é `[0, 1, 2]`. Imprima o quadrado de cada número em uma linha separada.

```
0
1
4
```
Formato da entrada

A entrada consiste de um número inteiro positivo `n`, informado pelo usuário.

Formato da saída

Imprima `n` linhas, cada qual com o valor correspondente de `i`.

Entrada

```
5
```

Saída

```
0
1
4
9
16
```
"""

numero = int(input())

count = 0

while count < numero:
  print(count**2)
  count += 1