# -*- coding: utf-8 -*-
"""LP2023 - Avaliação 01 - Exercício 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4X-NiKhghB_MzMMB3tobAZGABI7Jiij

Curso de Tecnologia em Análise e Desenvolvimento de Sistemas da Faculdade de Tecnologia de São José do Rio Preto
# Avaliação de Linguagem de Programação
## Prof. Dr. Henrique Dezani

---
### SUBMISSÃO

Para submeter a sua solução, siga as etapas:
1. Faça o download do código python clicando em File -> Download -> Download.py
2. Acesse o _link_
3. Faça o login usando seu número de matrícula
4. Faça o _upload_ do Exercício (arquivo que fez o _download_ do Colab na etapa 2). 

Não se esqueça de escolher o exerício correto durante a submissão.

---
### ENUNCIADO DO EXERCÍCIO 2

Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.
Observando os termos no plural a colocação do "e", da vírgula entre outros.

Examplo

Dado o valor de entrada igual a `326`, a saída esperada é:

```
3 centenas, 2 dezenas e 6 unidades
```
Formato da entrada

A entrada consiste de um número inteiro positivo `numero` menor que 1000, informado pelo usuário.

Formato da saída

Descrição, por extenso, do número.

Entrada

```
12
```

Saída

```
1 dezena e duas unidades
```
"""

# Desenvolva seu programa aqui:
n = int(input())

if (n >= 100):
  a = n / 100
  b = (n % 100) / 10
  c = n % 10
  if (int(a) == 1 and int(b) == 1 and int(c) == 1):
    print(f'{int(a)} centena, {int(b)} dezena e {int(c)} unidade')
  elif (int(a) == 1 and int(b) == 1 and int(c) != 1):
    print(f'{int(a)} centena, {int(b)} dezena e {int(c)} unidades')
  elif (int(a) == 1 and int(b) != 1 and int(c) != 1):
    print(f'{int(a)} centena, {int(b)} dezenas e {int(c)} unidades')
  elif (int(a) != 1 and int(b) == 1 and int(c) != 1):
    print(f'{int(a)} centenas, {int(b)} dezena e {int(c)} unidades')
  elif (int(a) != 1 and int(b) == 1 and int(c) == 1):
    print(f'{int(a)} centenas, {int(b)} dezena e {int(c)} unidade')
  elif (int(a) != 1 and int(b) != 1 and int(c) == 1):
    print(f'{int(a)} centenas, {int(b)} dezenas e {int(c)} unidade')
  elif (int(a) == 1 and int(b) != 1 and int(c) == 1):
    print(f'{int(a)} centena, {int(b)} dezenas e {int(c)} unidade')
  else:
    print(f'{int(a)} centenas, {int(b)} dezenas e {int(c)} unidades')

elif (n < 10):
  c = n
  if (int(c) == 1):
    print(f'{int(c)} unidade')
  else:
    print(f'{int(c)} unidades')

else:
  b = (n % 100) / 10
  c = n % 10
  if (int(b) == 1 and int(c) == 1):
    print(f'{int(b)} dezena e {int(c)} unidade')
  elif (int(b) == 1 and int(c) != 1):
    print(f'{int(b)} dezena e {int(c)} unidades')
  else:
    print(f'{int(b)} dezenas e {int(c)} unidades')