# -*- coding: utf-8 -*-
"""LP2023 - Avaliação 01 - Exercício 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4X-NiKhghB_MzMMB3tobAZGABI7Jiij

Curso de Tecnologia em Análise e Desenvolvimento de Sistemas da Faculdade de Tecnologia de São José do Rio Preto
# Avaliação de Linguagem de Programação
## Prof. Dr. Henrique Dezani

---
### SUBMISSÃO

Para submeter a sua solução, siga as etapas:
1. Faça o download do código python clicando em File -> Download -> Download.py
2. Acesse o _link_
3. Faça o login usando seu número de matrícula
4. Faça o _upload_ do Exercício (arquivo que fez o _download_ do Colab na etapa 2). 

Não se esqueça de escolher o exerício correto durante a submissão.

---
### ENUNCIADO DO EXERCÍCIO 2

Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.
Observando os termos no plural a colocação do "e", da vírgula entre outros.

Examplo

Dado o valor de entrada igual a `326`, a saída esperada é:

```
3 centenas, 2 dezenas e 6 unidades
```
Formato da entrada

A entrada consiste de um número inteiro positivo `numero` menor que 1000, informado pelo usuário.

Formato da saída

Descrição, por extenso, do número.

Entrada

```
12
```

Saída

```
1 dezena e duas unidades
```
"""

# Desenvolva seu programa aqui:
numero = int(input())
if numero < 1000:
  if numero < 10:
    if numero == 1:
      print('1 unidade')
    else:
      print(f'{numero} unidades')
  elif numero < 100:
    numero = str(numero)
    if '1' in numero:
      if '1' in numero[0] and '1' in numero[1]:
        print(f'1 dezena e 1 unidade')
      elif '1' in numero[0]:
        print(f'1 dezena e {numero[1]} unidades')
      elif '1' in numero[1]:
        print(f'{numero[0]} dezenas e 1 unidade')
  else:
    numero = str(numero)
    if '1' in numero:
      if '1' in numero[0] and '1' in numero[1] and '1' in numero[2]:
        print(f'1 centena, 1 dezena e 1 unidade')
      
      elif '1' in numero[0] and '1' in numero[1]:
        print(f'1 centena, 1 dezena e {numero[2]} unidades')

      elif '1' in numero[2] and '1' in numero[1]:
        print(f'{numero[0]} centenas, 1 dezena e 1 unidade')

      elif '1' in numero[2] and '1' in numero[0]:
        print(f'1 centena, {numero[1]} dezenas e 1 unidade')

      elif '1' in numero[0]:
        print(f'1 centena, {numero[1]} dezenas e {numero[2]} unidades')

      elif '1' in numero[1]:
        print(f'{numero[0]} centenas, 1 dezena e {numero[2]} unidades')

      elif '1' in numero[2]:
        print(f'{numero[0]} centenas, {numero[1]} dezenas e 1 unidade')

    else:
      print(f'{numero[0]} centenas, {numero[1]} dezenas e {numero[2]} unidades')