# -*- coding: utf-8 -*-
"""Cópia de LP2023 - Avaliação 01 - Exercício 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UNnS7W1CYZNvw0SnGd6qKQd4JbWlYc4w

Curso de Tecnologia em Análise e Desenvolvimento de Sistemas da Faculdade de Tecnologia de São José do Rio Preto
# Avaliação de Linguagem de Programação
## Prof. Dr. Henrique Dezani

---
### SUBMISSÃO

Para submeter a sua solução, siga as etapas:
1. Faça o download do código python clicando em File -> Download -> Download.py
2. Acesse o _link_
3. Faça o login usando seu número de matrícula
4. Faça o _upload_ do Exercício (arquivo que fez o _download_ do Colab na etapa 2). 

Não se esqueça de escolher o exerício correto durante a submissão.

---
### ENUNCIADO DO EXERCÍCIO 2

Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.
Observando os termos no plural a colocação do "e", da vírgula entre outros.

Examplo

Dado o valor de entrada igual a `326`, a saída esperada é:

```
3 centenas, 2 dezenas e 6 unidades
```
Formato da entrada

A entrada consiste de um número inteiro positivo `numero` menor que 1000, informado pelo usuário.

Formato da saída

Descrição, por extenso, do número.

Entrada

```
12
```

Saída

```
1 dezena e duas unidades
```
"""

# Desenvolva seu programa aqui:
numero = int(input('Digite um número inteiro menor que 1000: '))

centena = 0
dezena = 0
unidade = 0

if numero >= 1000:
  int(input('Escreva um número inteiro menor que 1000, por gentileza: '))
for centena in range(0, numero, 100):
  centena += 1
  for c in range(0, numero, 10):
    dezena += 1
    for c in range(0, numero, 1):
      unidade += 1
  print(f'{centena} centeza, {dezena} dezenas e {unidade} unidades!')

