# -*- coding: utf-8 -*-
"""Cópia de LP2023 - Avaliação 01 - Exercício 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0Ilhstmd5JoOzMirhIOv70iRP4D41Cb

Curso de Tecnologia em Análise e Desenvolvimento de Sistemas da Faculdade de Tecnologia de São José do Rio Preto
# Avaliação de Linguagem de Programação
## Prof. Dr. Henrique Dezani

---
### SUBMISSÃO

Para submeter a sua solução, siga as etapas:
1. Faça o download do código python clicando em File -> Download -> Download.py
2. Acesse o _link_
3. Faça o login usando seu número de matrícula
4. Faça o _upload_ do Exercício (arquivo que fez o _download_ do Colab na etapa 2). 

Não se esqueça de escolher o exerício correto durante a submissão.

---
### ENUNCIADO DO EXERCÍCIO 2

Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.
Observando os termos no plural a colocação do "e", da vírgula entre outros.

Examplo

Dado o valor de entrada igual a `326`, a saída esperada é:

```
3 centenas, 2 dezenas e 6 unidades
```
Formato da entrada

A entrada consiste de um número inteiro positivo `numero` menor que 1000, informado pelo usuário.

Formato da saída

Descrição, por extenso, do número.

Entrada

```
12
```

Saída

```
1 dezena e duas unidades
```
"""

# Desenvolva seu programa aqui:
numero = int(input("Digite um número inteiro menor que 1000: "))

if numero >= 1000:
    print("Número inválido. O valor deve ser menor que 1000.")
else:
    centenas = numero // 100
    dezenas = (numero % 100) // 10
    unidades = numero % 10

    texto_centenas = f"{centenas} centena" if centenas == 1 else f"{centenas} centenas"
    texto_dezenas = f"{dezenas} dezena" if dezenas == 1 else f"{dezenas} dezenas"
    texto_unidades = f"{unidades} unidade" if unidades == 1 else f"{unidades} unidades"

    resultado = ""

    if centenas > 0:
        resultado += texto_centenas

    if dezenas > 0:
        if resultado:
            resultado += ", "

        resultado += texto_dezenas

    if unidades > 0:
        if resultado:
            if centenas == 0 or dezenas == 0:
                resultado += " e "
            else:
                resultado += ", "

        resultado += texto_unidades

    print(resultado)