# -*- coding: utf-8 -*-
"""LP2023 - Avaliação 01 - Exercício 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i4X-NiKhghB_MzMMB3tobAZGABI7Jiij

Curso de Tecnologia em Análise e Desenvolvimento de Sistemas da Faculdade de Tecnologia de São José do Rio Preto
# Avaliação de Linguagem de Programação
## Prof. Dr. Henrique Dezani

---
### SUBMISSÃO

Para submeter a sua solução, siga as etapas:
1. Faça o download do código python clicando em File -> Download -> Download.py
2. Acesse o _link_
3. Faça o login usando seu número de matrícula
4. Faça o _upload_ do Exercício (arquivo que fez o _download_ do Colab na etapa 2). 

Não se esqueça de escolher o exerício correto durante a submissão.

---
### ENUNCIADO DO EXERCÍCIO 2

Faça um Programa que leia um número inteiro menor que 1000 e imprima a quantidade de centenas, dezenas e unidades do mesmo.
Observando os termos no plural a colocação do "e", da vírgula entre outros.

Examplo

Dado o valor de entrada igual a `326`, a saída esperada é:

```
3 centenas, 2 dezenas e 6 unidades
```
Formato da entrada

A entrada consiste de um número inteiro positivo `numero` menor que 1000, informado pelo usuário.

Formato da saída

Descrição, por extenso, do número.

Entrada

```
12
```

Saída

```
1 dezena e duas unidades
```
"""

# Desenvolva seu programa aqui:

numero = int(input())

if numero >= 100:

# Desenvolva seu programa aqui:

numero = int(input())
n = str(numero)

if 0 <= numero <= 1:
  c = n[0]
  print(f'{c} unidade')
if 2 <= numero <= 9:
  c = n[0]
  print(f'{c} unidades')
if 10 <= numero <= 19:
  c = n[0]
  d = n[1]
  print(f'{c} dezena e {d} unidades')
if numero == 20 or == 40 or numero == 50 or numero == 60
  c = n[0]
  d = n[1]
if (21 <= numero <= 29) or (31 <= numero <= 39) or (41 <= numero <= 49) or (51 <= numero <= 59) or (61 <= numero <= 69) or (71 <= numero <= 79) or (81 <= numero <= 89) or (91 <= numero <= 99):
  c = n[0]
  d = n[1]
  print(f'{c} dezena e {d} unidades')
if numero <= 200:
  c = n[0]
  d = n[1]
  u = n[2]
  print(f'{c} centena, {d} dezenas e {u} unidades')
if numero >= 201:
  c = n[0]
  d = n[1]
  u = n[2]
  print(f'{c} centenas, {d} dezenas e {u} unidades')